server:
  port: 9999
spring:
  application:
    name: getway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
      - id: user-service
        uri:  http://localhost:9998/
        predicates:
        - Path=/demo/**
      - id: swagger-doc
        uri:  http://localhost:8080/
        predicates:
        - Path=/test/**
      default-filters:
      - name: Hystrix
        args:
          name: default-hystrix
          #转发地址
          fallbackUri: forward:/fallback
      - name: Retry
        args:
          #重试次数，默认值是 3 次
          retries: 3
          #HTTP 的状态返回码
          statuses: BAD_GATEWAY,BAD_REQUEST
          #指定哪些方法的请求需要进行重试逻辑，默认值是 GET 方法
          methods: GET,POST
logging:
  level:
    com.*:  debug
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000